### ISSUE TITLE
Sum is not correct.

### ISSUE THREAD

**Issue by sapabg** [s3c4/angular-ts-math#1]
using angularMath.sum(n1, n2, n3, ...); returns the same sum as it would if I use a simple + operator which returns the wrong sum. Example:
ler arr =[0.32, 0.16, 0.16, 0.16, 0.02, 0.16];
angularMath.sum(...arr) returns 0.9800000000000001

**Comment by s3c4** [comment]
The issue is fixed in version 2.0.0
